# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: online-judge-secret
type: Opaque
stringData:
  JWT_SECRET: ""
  ADMIN_SECRET: ""
  ADMIN_EMAIL: ""
  ADMIN_PASSWORD: ""
  DB_URL: ""
  RABBITMQ_URL: ""